#!/usr/bin/env bash

if ! command -v dotbot &> /dev/null; then
		echo "dotbot not found, install it using pip3"
		if ! command -v pip3 &> /dev/null; then
				echo "pip3 not found, installing..."
				sudo apt install python3-pip
				CMD="$HOME/.local/bin/dotbot"
		fi
		pip3 install -i https://pypi.doubanio.com/simple/ \
				--trusted-host pypi.doubanio.com dotbot
else
		CMD=$(which dotbot)
		echo "use dotbot in $CMD"
fi

$CMD -c `pwd`/install.conf.yaml

